#
# Copyright (C) 2025 Texas Instruments Incorporated - https://www.ti.com/
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= pocketbeagle2.o
obj-${CONFIG_TI_I2C_BOARD_DETECT} += ../../ti/common/board_detect.o
obj-$(CONFIG_PHYTEC_K3_DDR_PATCH) += ../../phytec/common/k3/k3_ddrss_patch.o
