# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2015-2016 Texas Instruments Incorporated - http://www.ti.com/

obj-${CONFIG_TI_I2C_BOARD_DETECT} += board_detect.o
obj-${CONFIG_CMD_EXTENSION} += cape_detect.o
obj-$(CONFIG_SET_DFU_ALT_INFO) += k3_dfu.o
obj-${CONFIG_ARCH_K3} += k3-ddr-init.o
obj-${CONFIG_BOARD_HAS_32K_RTC_CRYSTAL} += rtc.o
